config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/index'

  get 'documents/show'

  get 'documents/new'

  get 'documents/create'

  get 'documents/edit'

  get 'documents/update'

  get 'dues' => 'transactions#new'
  
  post 'dues' => 'transactions#create'

  get 'payment_history' => 'transactions#index'
  
  get 'user_payment_history' => 'transactions#show'
  
  get 'profile' => 'users#profile'
  
  post 'confirm' => 'transactions#confirm'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :announcements
  resources :account_activations, only: [:edit, :index]
  resources :transactions
  resources :documents
  
  root "static_pages#home"
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'sign_up' => 'users#new'
  
  get 'brothers' => 'users#index'
  
  get 'calendar' => 'static_pages#calendar'
  
  post 'approve' => 'account_activations#approve'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
    validates :title, presence: true, length: {minimum: 5}
    validates :content, presence: true, allow_blank: false
    
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    before_action :require_login
    
    # landing; lists all of a User's announcements
    def index
        @announcements = Announcement.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
    end
    
    # create a new announcement for a form
    def new
        @announcement = Announcement.new
    end
    
    # Handle announcement form submission
    def create
        @announcement = Announcement.new(post_params)
        @announcement.created_by = current_user.name
        
        if @announcement.save
            redirect_to announcements_path
        else
            render 'new'
        end
    end
    
    # Retrieve post to show
    def show
        @announcement = Announcement.find(params[:id])
    end
    
    # Setup post editing
    def edit
        @announcement = Announcement.find_by(id: params[:id])
    end
    
    # Update announcement method
    def update
        @announcement = Announcement.find(params[:id])
        
        if @announcement.update(params.require(:announcement).permit(:title, :content))
            redirect_to @announcement
        else
            render 'edit'
        end
    end
    
    # Destroy announcement
    def destroy
        
        @announcement = Announcement.find_by(id: params[:id])
        @announcement.destroy
        
        redirect_to announcements_path
    end
    
    
    private
    
    # ensure that secure submission
    def post_params
        params.require(:announcement).permit(:title, :content)
    end
    
    
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement, url: announcements_path do |f| %> 
        <% if @announcement.errors.any? %>
          <div id="errors">
            <h2><%= pluralize(@announcement.errors.count, "error") %> prevented this post from saving:</h2>
            <ul>
              <% @announcement.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class = 'form-group'>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        </div>
        
        <div class = 'form-group'>
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
        </div>
        
        
        <%= f.submit "Post", class: "btn btn-warning btn-block" %>
<% end %>

app/views/announcements/edit.html.erb
<div id="page_wrapper">
  <h1 class = "page_header">Edit Post</h1>
 
  <%= render 'announcements/form' %>
</div>

app/views/announcements/index.html.erb
<div id = "page_wrapper">
  <h2 class = "page_header">Announcements</h2>
  <% @announcements.each do |announce| %>
    <div class="announce_wrapper">
      <h3 class="title"><%= link_to announce.title, announce %></h3>
      <p class="date"><%= announce.created_at.strftime("%B %d, %Y") %> by <%= announce.created_by %></p>
      <p class="body">
        <%= announce.content %>
      </p>   
    </div>
  <% end %>
  <%= will_paginate @posts, class: "apple_pagination" %>
</div>

app/views/announcements/new.html.erb
<div id = "page_wrapper">
    
    <h1 class = "page_header">New Announcement</h1>
    
    <%= render 'announcements/form' %>
</div>
    

app/views/announcements/show.html.erb
<div id = "page_wrapper">
    <div class = "announce_wrapper">
        <h2 class = "title">
            <%= @announcement.title %>
        </h2>
    
        <p class="body">
          <%= @announcement.content %>
        </p>   
        
        <p class = "date">
            Posted <%= @announcement.created_at %> by <%= @announcement.created_by unless !@announcement.created_by %>
            <% if (logged_in? && current_user.admin == 1) %>
            | <%= link_to 'Edit', edit_announcement_path(@announcement) %> |
              <%= link_to 'Delete', announcement_path(@announcement), method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
        </p>
    </div>
</div>


    