config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/index'

  get 'documents/show'

  get 'documents/new'

  get 'documents/create'

  get 'documents/edit'

  get 'documents/update'

  get 'dues' => 'transactions#new'
  
  post 'dues' => 'transactions#create'

  get 'payment_history' => 'transactions#index'
  
  get 'user_payment_history' => 'transactions#show'
  
  get 'profile' => 'users#profile'
  
  post 'confirm' => 'transactions#confirm'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :announcements
  resources :account_activations, only: [:edit, :index]
  resources :transactions
  resources :documents
  
  root "static_pages#home"
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'sign_up' => 'users#new'
  
  get 'brothers' => 'users#index'
  
  get 'calendar' => 'static_pages#calendar'
  
  post 'approve' => 'account_activations#approve'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  before_action :require_login
  before_action :require_admin, only: [:index, :confirm]
  
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.create(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.created_by = current_user.email
    @transaction.email = current_user.email
    @transaction.convert params[:transaction][:amount]
    if @transaction.save
      flash.now[:notice] = "Thank you for your payment, you will receive a confirmation soon."
      redirect_to @transaction.paypal_url(root_url)
    else
      render 'new'
    end
  end

  def confirm
    @transaction = Transaction.find_by(id: params[:id])
    @transaction.confirmed = true
    @transaction.confirmed_by = current_user.name;
    @transaction.confirmed_at = Time.now;
    if @transaction.save
      @transaction.send_confirm_email
    else
      flash.now[:danger] = "Confirmation failed"
    end
    redirect_to payment_history_path
    
  end
  
  def destroy
    @transaction = Transaction.find_by(id: params[:id])
    @transaction.destroy
    
    redirect_to payment_history_path
  end

  def index
    @transactions = Transaction.all.order('confirmed').order('created_at ASC').paginate(page: params[:page], :per_page => 20)
  end

  def show
    @transactions = current_user.transactions.all.paginate(page: params[:page], per_page: 20)
  end
  
  private 
  
  def transaction_params
    params.require(:transaction).permit(:id, :amount, :kind)
  end
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/confirm.html.erb
<h1>Transactions#confirm</h1>
<p>Find me in app/views/transactions/confirm.html.erb</p>

app/views/transactions/index.html.erb
<div id = "page_wrapper">
    <div class = "page_header">
        <h3>Confirm Transactions</h3>
    </div>
    <div class = "payment_history_table">
        <% if @transactions.empty? %>
        <div class = "page_header">
            Nothing to show!
        </div>
        <% else %> 
        <table class = "table" id = "transactions">
            <tr>
                <th>Transaction No.</th>
                <th>Date</th>
                <th>Name</th>
                <th>Email</th>
                <th>Amount</th>
                <th>Confirmed?</th>
            </tr>
            
            <% @transactions.each do |t| %>
            <tr>
                <td><%= t.id %></td>
                <td><%= t.created_at%></td>
                <td><%= t.user.name %></td>
                <td><%= t.user.email %></td>
                <td><%= number_to_currency t.amount %></td>
                <td>
                    <% if t.confirmed %>
                    Confirmed by <%= t.confirmed_by %> at <%= t.confirmed_at %>
                    <% else %>
                    <h4><%= link_to "click to confirm", {action: "confirm", id: t.id}, method: 'post' %></h4>
                    <%= link_to 'Click to Delete', transaction_path(t), method: :delete, data: {confirm: 'Are you sure?'} %>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </table>
        <% end %>
    </div>
    <%= will_paginate @transactions, class: "apple_pagination"%> 
</div>

app/views/transactions/new.html.erb
<div id = "page_wrapper">
    
    <div class = "page_header">
        <h2>Pay Dues</h2>
    </div>
    <div class = "page_header">
        <h7>NOTE: Paying online incurs a transaction fee. To avoid this fee, please contact the Undergraduate Treasurer to pay by cash or check.</h7>
        <h7>Brothers interested in financial aid, please contact the Undergraduate Treasurer.</h7>
    </div>
    
    <%= form_for(@transaction, url: dues_path) do |f| %>
        
        <%= render 'shared/error_messages' %> 
        
        <div class = "form-group">
        <%= f.label :amount %>
        <%= f.select :amount, ["Dues: $400", "New Brother Dues: $550"], include_blank: "Choose amount", class: "form-control" %>
        </div>
        
        <%= f.submit "Submit", class: "btn btn-primary" %>
    
    <% end %>
</div>
    

app/views/transactions/show.html.erb
<div id = "page_wrapper">
    <div class = "page_header">
        <h3>Your Transaction History</h3>
    </div>
    <div class = "payment_history_table">
        <% if @transactions.empty? %>
        <div class = "page_header">
            Nothing to Show
        </div>
        <% else %>
        <table class = "table" id = "transactions">
            <tr>
                <th>Transaction No.</th>
                <th>Name</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Confirmed?</th>
            </tr>
            
            <% @transactions.each do |t| %>
            <tr>
                <td><%= t.id %></td>
                <td><%= t.user.name %> </td>
                <td><%= t.created_at%></td>
                <td><%= number_to_currency t.amount %></td>
                <% if t.confirmed %>
                <td>Confirmed by <%= t.confirmed_by %></td>
                <% else %>
                <td>Not Confirmed</td>
                <% end %>
            </tr>
            <% end %>
        </table>
        <% end %>
    </div>
    <%= will_paginate @transactions, class: "apple_pagination"%> 
</div>