config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/index'

  get 'documents/show'

  get 'documents/new'

  get 'documents/create'

  get 'documents/edit'

  get 'documents/update'

  get 'dues' => 'transactions#new'
  
  post 'dues' => 'transactions#create'

  get 'payment_history' => 'transactions#index'
  
  get 'user_payment_history' => 'transactions#show'
  
  get 'profile' => 'users#profile'
  
  post 'confirm' => 'transactions#confirm'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :announcements
  resources :account_activations, only: [:edit, :index]
  resources :transactions
  resources :documents
  
  root "static_pages#home"
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'sign_up' => 'users#new'
  
  get 'brothers' => 'users#index'
  
  get 'calendar' => 'static_pages#calendar'
  
  post 'approve' => 'account_activations#approve'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  
end

app/views/layouts/_header.html.erb
<div id="header">
    
    <p class = "logo">The Oak Club </p>
 
    <div class="buttons">
    <% if logged_in? %>
      <p>Welcome, <%= current_user.name %></p>
      <%= link_to logout_path do %>
        <button class = "btn btn-warning">Log Out</button>
      <% end %>
    <% else %>
      <%= link_to sign_up_path do %>
        <button class = "btn btn-warning">Sign Up</button>
      <% end %>
      <%= link_to login_path do %>
        <button class = "btn btn-warning">Log In</button>
      <% end %>
    <% end %>
    </div>
    
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
            <%= site_logo %>
        <% end %>
      </div>
      
      <% if logged_in? %>
      <ul>
        
        <% if current_user.admin == 1 %>
        <li class="category">Admin</li>
        <li><%= link_to "Post an Announcement", new_announcement_url %></li>
        <li><%= link_to "Approve accounts", account_activations_url %></li>
        <li><%= link_to "Confirm transactions", payment_history_url %></li>
        <li><%= link_to "Manage Documents" %></li>
        <% end %>
        
        <li class="category">Navigation</li>
        <li><%= link_to "Announcements", announcements_url %></li>
        <li><%= link_to "Club Calendar", calendar_url %></li>
        <li><%= link_to "Brother Database", brothers_url %></li>
        <li><%= link_to "Pay Dues", dues_url %></li>
        <li><%= link_to "Transaction History", user_payment_history_url %></li>
        <li><%= link_to "Documents" %></li>
        
        <li class="category">Profile</li>
        <li><%= link_to "View your profile", profile_url %></li>
        <li><%= link_to "Edit your profile", edit_user_url(@current_user) %></li>
        
      </ul>
      <% end %>
 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Oak Club</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %> 
</head>
<body>
  <%= render 'layouts/sidebar' %>
  
  
  <div id="main_content">
    <%= render 'layouts/header'%>
 
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>
    
    

    <%= yield %>
    
    <%=  debug params if Rails.env.development? %>
  </div>

</body>
</html>